# Generated by Django 2.2.19 on 2022-05-20 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo', '0002_auto_20220511_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='In_memories',
            new_name='InMemories',
        ),
    ]
