# Generated by Django 3.2 on 2022-06-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_auto_20220519_1317'),
        ('memo', '0003_auto_20220520_1048'),
    ]

    operations = [
    ]
